name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main  # ou la branche de votre choix
    paths:
      - 'Dockerfile'  # ou tous les fichiers nécessaires à la build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Se connecter à GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Utilise le GITHUB_TOKEN pour l'authentification

      # Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/gns3-alpine:latest .

      # Pousser l'image Docker vers GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/gns3-alpine:latest
