name: Build and Push Docker Image to GHCR

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Se connecter à GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Utilise le GITHUB_TOKEN pour l'authentification

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      # Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$OWNER_LC/gns3-alpine:latest gns3-alpine/

      # Pousser l'image Docker vers GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/$OWNER_LC/gns3-alpine:latest
